# Generated by Django 4.0.5 on 2022-06-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
