# Generated by Django 4.0.5 on 2022-06-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('ISBN', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=700, null=True)),
                ('price', models.IntegerField(max_length=150, null=True)),
                ('edition', models.CharField(max_length=150, null=True)),
                ('publisher', models.CharField(max_length=150, null=True)),
                ('publishers', models.CharField(max_length=159)),
            ],
        ),
    ]
